FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

COPY ["BackgroundWorker/BackgroundWorker.csproj", "BackgroundWorker/"]
COPY ["Shared/Shared.csproj", "Shared/"]
RUN dotnet restore "BackgroundWorker/BackgroundWorker.csproj"

COPY . .
WORKDIR "/source/BackgroundWorker"
RUN dotnet publish "BackgroundWorker.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BackgroundWorker.dll"]